version: "3.1"

services:
  docker-registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - /Users/user/mnt/registry/data:/var/lib/registry
  pgdatabase:
    image: postgres:10.4
    container_name: pgdatabase
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: man
      POSTGRES_DB: appear
      PGDATA: /mnt/database
    volumes:
      - /Users/user/mnt/database:/mnt/database
    ports:
      - "5432:5432"